### PR TITLE
simplify user creation, build with 1.17

### PR DESCRIPTION
**Pull request by majst01**
User creation automatically creates a matching os group, therefore group creation is not required.
IMHO it is also not required to create groups on the OS level which match the roles, skip this as well.

### CODE REVIEW

**Comment by michaelottofits** [comment]
@majst01 
The user group that is created is not relevant.
Groups and memberships should be assigned from roles claim in the OIDC ticket. 
the source text is now simple but does not work.
Log messages: 

```
Oct  5 15:24:37 dexidp pam-exec-oauth2[85647]: 2021/10/05 15:24:37 using config file:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml
Oct  5 15:24:37 dexidp pam-exec-oauth2[85647]: 2021/10/05 15:24:37 useradd command was not found exec: "useradd": executable file not found in $PATH
Oct  5 15:24:49 dexidp pam-exec-oauth2[85732]: 2021/10/05 15:24:49 using config file:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml
Oct  5 15:24:49 dexidp pam-exec-oauth2[85732]: 2021/10/05 15:24:49 useradd command was not found exec: "useradd": executable file not found in $PATH
```

**Comment by majst01** [comment]
> @majst01 The user group that is created is not relevant. Groups and memberships should be assigned from roles claim in the OIDC ticket. the source text is now simple but does not work. Log messages:
> 
> ```
> Oct  5 15:24:37 dexidp pam-exec-oauth2[85647]: 2021/10/05 15:24:37 using config file:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml
> Oct  5 15:24:37 dexidp pam-exec-oauth2[85647]: 2021/10/05 15:24:37 useradd command was not found exec: "useradd": executable file not found in $PATH
> Oct  5 15:24:49 dexidp pam-exec-oauth2[85732]: 2021/10/05 15:24:49 using config file:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml
> Oct  5 15:24:49 dexidp pam-exec-oauth2[85732]: 2021/10/05 15:24:49 useradd command was not found exec: "useradd": executable file not found in $PATH
> ```
hard-coded the path to useradd for now, make it work first then make it distribution agnostic.

**Comment by michaelottofits** [comment]
@majst01 

next test failed too:

the pam login via oidc no longer works. It looks like when it detects that it has already terminated the user.


Log Messages: 
```
Oct  5 16:22:33 dexidp pam-exec-oauth2[126230]: 2021/10/05 16:22:33 using config file:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml
Oct  5 16:22:33 dexidp pam-exec-oauth2[126230]: 2021/10/05 16:22:33 unable to create user output:useradd: user 'iz00710' already exists#012 exit status 9

```
why do you have to give the whole path for searching a binary to find the path ?

`exec.LookPath("/usr/sbin/useradd")`

in branch usermanagement i use 
`pathuseradd, errorfindpath := exec.LookPath("useradd")`

**Comment by majst01** [comment]
> @majst01
> 
> next test failed too:
> 
> the pam login via oidc no longer works. It looks like when it detects that it has already terminated the user.
> 
> Log Messages:
> 
> ```
> Oct  5 16:22:33 dexidp pam-exec-oauth2[126230]: 2021/10/05 16:22:33 using config file:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml
> Oct  5 16:22:33 dexidp pam-exec-oauth2[126230]: 2021/10/05 16:22:33 unable to create user output:useradd: user 'iz00710' already exists#012 exit status 9
> ```
> 
> why do you have to give the whole path for searching a binary to find the path ?
> 
> `exec.LookPath("/usr/sbin/useradd")`
> 
> in branch usermanagement i use `pathuseradd, errorfindpath := exec.LookPath("useradd")`

Now, user creation was triggered, but my user already exists detection not, wait a second

**Comment by majst01** [comment]
Your branch is also 7 commits behind master, and this branch is based on yours, so we also need to pull from master first

**Pull request closed without merging**
